server:
  port: 8080

jwt:
  secret: "app-medica-duoc-2026-app-medica-duoc-2026"
  expiration-minutes: 60

spring:
  application:
    name: ms-api-gateway

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: pacientes-bff
              uri: ${PACIENTES_BFF_URI:http://localhost:8181}
              predicates:
                - Path=/api/v1/pacientes/**

            - id: citas-bff
              uri: ${CITAS_BFF_URI:http://localhost:8090}
              predicates:
                - Path=/api/v1/citas/**

            - id: historial-bff
              uri: ${HISTORIAL_BFF_URI:http://localhost:9090}
              predicates:
                - Path=/api/v1/historiales/**