server:
  port: 8080

jwt:
  secret: "app-medica-duoc-2026-app-medica-duoc-2026"
  expiration-minutes: 60

springdoc:
  swagger-ui:
    urls-primary-name: Auth
    urls:
      - name: Auth
        url: /v3/api-docs
      - name: Pacientes
        url: /pacientes-docs/v3/api-docs
      - name: Citas
        url: /citas-docs/v3/api-docs
      - name: Historial
        url: /historial-docs/v3/api-docs

spring:
  application:
    name: ms-api-gateway

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: pacientes-bff
              uri: ${PACIENTES_BFF_URI:http://localhost:8181}
              predicates:
                - Path=/api/v1/pacientes/**

            - id: citas-bff
              uri: ${CITAS_BFF_URI:http://localhost:8090}
              predicates:
                - Path=/api/v1/citas/**

            - id: historial-bff
              uri: ${HISTORIAL_BFF_URI:http://localhost:9090}
              predicates:
                - Path=/api/v1/historiales/**

            - id: pacientes-docs
              uri: ${PACIENTES_BFF_URI:http://localhost:8181}
              predicates:
                - Path=/pacientes-docs/**
              filters:
                - RewritePath=/pacientes-docs/(?<segment>.*), /${segment}

            - id: citas-docs
              uri: ${CITAS_BFF_URI:http://localhost:8090}
              predicates:
                - Path=/citas-docs/**
              filters:
                - RewritePath=/citas-docs/(?<segment>.*), /${segment}

            - id: historial-docs
              uri: ${HISTORIAL_BFF_URI:http://localhost:9090}
              predicates:
                - Path=/historial-docs/**
              filters:
                - RewritePath=/historial-docs/(?<segment>.*), /${segment}